#ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community

  #ThymeleafProperties
spring:
  thymeleaf:
    cache: false

  #mail
  mail:
    username: 1797532878@qq.com
    password: ojaftpbpacvpccde
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          port: ${spring.mail.port}
          auth: true
          starttls:
            enable: true
            required: true


  # DataSourceProperties
  #mysql 驱动   useSSL 不启用安全连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari.maximum-pool-size: 15
    hikari.minimum-idle: 5
    hikari.idle-timeout: 30000

  # MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #mapper文件映射的实体类地址
  type-aliases-package: com.nowcoder.community.entity
  #自动生成主键id
  configuration:
    useGeneratedKeys: true
  #驼峰命名法
    mapUnderscoreToCamelCase: true



  #logger
logging:
  level:
    com.nowcoder.community: debug

#community
community:
  path:
    domain: http://localhost:8080